[theme]
primaryColor = "#009BFF"
backgroundColor = "#090A0F"
secondaryBackgroundColor = "#0E1117"
textColor = "#FCFCFC"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
