[theme]
primaryColor = "#3ECFB4"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#111113"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
